module.exports = {
	ICON_BACK:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAGFBMVEX///////////////////////////////8pK8DIAAAACHRSTlMAESKqu8zd/03vFLEAAAAJcEhZcwAACvAAAArwAUKsNJgAAAAgdEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1Yu5EqJAAAAE9JREFUeJxjYBhWgFGBCEWiSUQYFF5G2CjR8nIDwgaVlwoQYVDgqEGjBg0ag0SIMIg4RURZR5TDR40aNWpgjSJY2BNXbRBVATEwEmHQUAAAq+06kWIjJWUAAAAASUVORK5CYII=',

	ICON_GO:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAFVBMVEX///////////////////////////9nSIHRAAAAB3RSTlMAESKqzN3/hRiFmAAAAAlwSFlzAAAK8AAACvABQqw0mAAAACB0RVh0U29mdHdhcmUATWFjcm9tZWRpYSBGaXJld29ya3MgTVi7kSokAAAAR0lEQVR4nGNgGBaASYAIRaqORBgUlkLYKOa0NMJGMbqlEWGUyKhRo0YNA6OIUUSUdaMGjRo0qAwiqrAnqtogqgIiriobQgAArH4x0amKFXsAAAAASUVORK5CYII=',

	ICON_GO_OFFSET:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAFVBMVEX///////////////////////////9nSIHRAAAAB3RSTlMAESKqzN3/hRiFmAAAAAlwSFlzAAAK8AAACvABQqw0mAAAACV0RVh0U29mdHdhcmUATWFjcm9tZWRpYSBGaXJld29ya3MgTVggMjAwNId2rM8AAABISURBVHicY2AYZkCRCDVMIQKEFammORJWZJaWQtgokTQijGJ0GzVq1KihbxRRioixbtSgUYMGlUHEFfZEVRtEVUBEVWWDHwAAUHwx79OU8rgAAAAASUVORK5CYII=',

	ICON_JUMP:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAGFBMVEX///////////////////////////////8pK8DIAAAACHRSTlMAESKqu8zd/03vFLEAAAAJcEhZcwAACvAAAArwAUKsNJgAAAAgdEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1Yu5EqJAAAAJdJREFUeJztz7ENgCAQheHDCSy0NzFxADdwBCt7GydQ1teAKMfdcRaWvA7C/0UB/l5f0zsz4nO1zfRRe3ToPNidUGaxK46sJRS5u6qUYq4oxeCkYyAacl+ZliyUpiyUtAKEYwFCtQjFuQhFfQZ6gQz0CFkoEFnoNhTIIwrkKQ1ylAY5SoXUXwuUDgE0k/4GzAeorKysTNoJym86giWhNfUAAAAASUVORK5CYII=',

	ICON_JUMP_SELECTED:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAGFBMVEX///////////////////////////////8pK8DIAAAACHRSTlMAESKqu8zd/03vFLEAAAAJcEhZcwAACvAAAArwAUKsNJgAAAAgdEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1Yu5EqJAAAAKpJREFUeJzt0j0OwjAMBWCHE3QoO1KlHqA34AhM7CycoPX1WzUE4vivlSJgqLdY731KpADUnq7huzDQ8+l546HzdCHnHkdGhTs+aAmRUWy3tEpKWHFKwFlPgHhRumXZFKGyKkJFV4FoWYFIW4XyugplfQP6AAb0FkwoESb0MhwoIg4UKQ9aKQ9aKRdyn5YoHwJor34GwgboC4PG/C6k3/YIHaH9of/741VmBr2QwGLt2oKWAAAAAElFTkSuQmCC',

	ICON_CLEAR:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAFVBMVEX///////////////////////////9nSIHRAAAAB3RSTlMAM0RVZqr/s5qSPgAAAAlwSFlzAAALEgAACxIB0t1+/AAAACB0RVh0U29mdHdhcmUATWFjcm9tZWRpYSBGaXJld29ya3MgTVi7kSokAAAAvUlEQVR4nO2UOw6EMAwFDVl6jsARUqXeipqKCwC+/xE2XonweZZ4dBS4SAGjAduxRd54fPR6DmQ+wDgQihByRAhl0ff4BKEsmuUKQhFCjgghRwRQEbV2VD60iprJzjR4UBGNGkWCLh60imrVrEqqHUJbavl9DH8SoC01AwxEaF+jZC2bnOz2NQoGRYTCodipiO5D1Oe4H6dKwBWTagvXYOqqcJeOur7cIFAjxQ0nNebcwqBWD7fEqHX4xlPiB4F9kpWeFoM0AAAAAElFTkSuQmCC',

	ICON_SELECT_CURRENT:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAGFBMVEX///////////////////////////8AAKoflqwsAAAACHRSTlMAM1Vmd4j//8O1NiUAAAAJcEhZcwAACvAAAArwAUKsNJgAAAAgdEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1Yu5EqJAAAANtJREFUeJztljESwjAMBA2BoeUJPCFVaipqKj4QuJqO72PLVjAJko8+13jGWm8aW0oImv2YVyCvwzUsc0NfQx0eS2YDjDU0AMclFXf7D9Tpme/odob0iKESyBBNBYEskVYSZIq0lCBbVGoRckRFFSFPlFWAK8oqwBeJKsUTiSrFFRWVLyqqhkhULZGomqKoaotC2J6MwuFl5LlCK/Q/VMe8dHWY60s9BOZJUY+TeeZUw2BaD9XEmHZINVamRVPNnhkb1ABiRhk1FJnxyg3qy3zk3398bjf/eThPpTcCHSGY7xxKegAAAABJRU5ErkJggg==',

	ICON_SELECT_UP:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAElBMVEX///////////////////////+65XQCAAAABnRSTlMAM1Vmd/910o15AAAACXBIWXMAAArwAAAK8AFCrDSYAAAAIHRFWHRTb2Z0d2FyZQBNYWNyb21lZGlhIEZpcmV3b3JrcyBNWLuRKiQAAACZSURBVHic7c67FcIwDIVhBzNARmAEGvU0TJDc/VfBehUcbCllwrFK34+flPI3d3scQLTlpgLPPASkqRbKU8QoSUkoS5GiMNVCG0BximeghilZgRKmZGwoSunWUJTSidE4ZQujccoGQaOUvwsapfxZUT+1+Ksi/s36q97WN1Sxd/7ubnlDhV69L1+/0dIzfo7Cm2iiiU6KLnIfZfo+OqWzTpAAAAAASUVORK5CYII=',

	ICON_SELECT_DOWN:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAElBMVEX///////////////////////+65XQCAAAABnRSTlMAM1VmiP/m9nALAAAACXBIWXMAAArwAAAK8AFCrDSYAAAAIHRFWHRTb2Z0d2FyZQBNYWNyb21lZGlhIEZpcmV3b3JrcyBNWLuRKiQAAACVSURBVHic7cyxFYAgDEVRUAdwBEegsbdxAv37ryIEonI0wRYPvySPa8xvBrSoRS2qMBrzyL41w5ZH8/ISrXD3qMf+bCyw3aMZGJ+Vf3VX1POffPwcI/4iUBQJ0HmgSIL4EiIR4lOIZCjdfKRAifKRBkUKUKFIATpEVJgGERWmQonSoUQVIKJKEFFFyFNlyJhu+hBVsgNWEj467EESXQAAAABJRU5ErkJggg==',

	ICON_CUE_INSERT:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAMFBMVEX///////////////////////////////////////////////////////////////9Or7hAAAAAEHRSTlMAESIzRFVmd4iZqrvM3e7/dpUBFQAAAAlwSFlzAAAK8AAACvABQqw0mAAAACB0RVh0U29mdHdhcmUATWFjcm9tZWRpYSBGaXJld29ya3MgTVi7kSokAAABQklEQVR4nO3TP0oDQRQG8DdqYvxTDEjETnsbTyBrpZ14AdfcwQOksdYTiNgqwRNkey1ygiQoChICUygEdtf9nM26ee4yMwQbm/2qV/x25/FmHlGVKtPAkf9D9m4r5ETi6P7pQrrRZpBOe9xyofogu5PYgUQHSPp95by7XWDkEW10HEgECHfSYrELSAtaRdLKqoZC24J8vOblKd4YlXKWf7mMWFpQOPu9bs+zoBfuYR8PFnTFaA3PZIqPPUY1fBrRZSIZCTUxouCLGyBS4RxoGBlRr4jivx83V+N+NuQMLeHDiLZxw8g2zHXztRRTV5GcIb7gYsSQn0oDkTQiOuaX5nNZyopK2lm19ev5ls/TizB9CAsBzKNMk67UAVFTr/GtFdG1Xs7xQC/nu91Qrfez5p4DUbObmtGJy+jmD+8ez/MRfQNFbrVE2ACzGAAAAABJRU5ErkJggg==',

	ICON_CUE_CLONE:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAJFBMVEX////////////////////////////////////////////////Vd7HLAAAADHRSTlMAESJEVWaImbvM7v88U0KyAAAACXBIWXMAAArwAAAK8AFCrDSYAAAAIHRFWHRTb2Z0d2FyZQBNYWNyb21lZGlhIEZpcmV3b3JrcyBNWLuRKiQAAABuSURBVHicY2CgP9iNBwycItyuHYmKcHFGFSEzvUFpaAt2RfAUxgGiGlCEMBUxgSgFAooYsnfv3sZASJHU7t0LsSpCBqy7dwdglUABs3cSVsNgvZkIRewF2MWpmYOppwiXL0YVjSoiR9HgS+P0AwCppKcBJcYC+wAAAABJRU5ErkJggg==',

	ICON_CUE_DELETE:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAMFBMVEX///////////////////////////////////////////////////////////////9Or7hAAAAAEHRSTlMAESIzRFVmd4iZqrvM3e7/dpUBFQAAAAlwSFlzAAAK8AAACvABQqw0mAAAACB0RVh0U29mdHdhcmUATWFjcm9tZWRpYSBGaXJld29ya3MgTVi7kSokAAABhUlEQVR4nO2TvU4CURCFZxVWRIpNDMZOehuewGClHfEFXHkCKOylsdYnMMZWAz4Bayi14AmAaDQxhGQL/EnYdY8zC2SF3HtbG06xmWS/3Dn3zB2ipZaKBYP+D9K7XUJGyDq8ezp3zNCWJ2kPKybI7k1mEhogqwFE3a5vnN0uMCgRbTYMkOVhXJBitQU4GiiLqDKpMj7qGsjF66w8xlsCLehk9mcNoaOBxkQp4Wpir6SBXojKX+wtINrDvQa6pJS0bOKBNvBMKrkokg18ZsFAGh9K6CJir1Wgg7BAlv+thLwf/tjSts2FP9ZD3FQOIuoHSqgTQzkgbtQPDSc1p5lq2sXGs+KJs9IZdyXkJsIzOSqFkRLawTXPDG2+4EgbZk7G4vHVqqj9Gcu8bD9wKMegzXaSAc/L6su15IUUKYPAUUJUTl6am5QLWvej+qTa/vN8F/vxIhSlWPGgjlIkK7VPlOc1vtFCdMXLOezxcr7rGUp3pmteMkCUbwkzODIxbP7g9vF0FtEvek22Eq8W+gsAAAAASUVORK5CYII=',

	ICON_UNDO:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAIVBMVEX///////////////////////////////////////////9/gMdvAAAAC3RSTlMAESIzVWaIu93u/3I6PYEAAAAJcEhZcwAACvAAAArwAUKsNJgAAAAgdEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1Yu5EqJAAAAKxJREFUeJztlDEOwjAQBB0B4QM8IE+gRFSpqahT0SHxAGpqOkRDjyBhXhlR+tbRuUTCW4/GJ/u8IZTEmeVA3cFnFrwzRLD2RbxyRPsi+i1RnMdZX3pnIRjaDIi+8Y775u4NvjqiC6hXsIGbpwrhRG8hVdXQuqrqysVXbXlaSFXLxC8UVa2Tq2rOoJBVVXwUEhUkIKtKQrYw0pCpnjRkSmwCiutwAopToDzoPzICBe2PkPCJqrEAAAAASUVORK5CYII=',

	ICON_REDO:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAIVBMVEX///////////////////////////////////////////9/gMdvAAAAC3RSTlMAESIzVWaIu93u/3I6PYEAAAAJcEhZcwAACvAAAArwAUKsNJgAAAAgdEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1Yu5EqJAAAALFJREFUeJztlC0OAjEQRht2IUiusQ4LCm6AXoUjQaEQa1HsEbD8hLxTbu1Mp5lKEvrJ5uV1Mp1OCDVm1gXM4l0AnTm4TAMFqp4C1byqfkfVnO6oJKp21Ai8FDMbUiaBNgajr4uDxnXvFN7BTZ4YLRj4rLwOtHB0RUu+8sBq5ZanK4o/7eKKYt2yJPN1R3auKDwQDbDHBHyRgjLzJqDcwpCmzOqRUGaJSSizDhVkp0J/nQlt05ByT4pUOgAAAABJRU5ErkJggg==',

	ICON_UNLOCK:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAMFBMVEX///////////////////////////////////////////////////////////////9Or7hAAAAAEHRSTlMAESIzRFVmd4iZqrvM3e7/dpUBFQAAAAlwSFlzAAAK8AAACvABQqw0mAAAACB0RVh0U29mdHdhcmUATWFjcm9tZWRpYSBGaXJld29ya3MgTVi7kSokAAAAp0lEQVR4nGNgGFDAXLnv7Q4DAmr2/weCvwH41DCt/w8GvxXwKNL9DwWP8Rj0/v//bY6iXUBVuJ2l9///ZhBt+///Q5yK1v//AWHM//8HlxqW//8bICyO//9xeZDn/28oi/H+/ws4FEm8/wRj2v//jMs+tgIYixvmOnyAHW4zHsD6/y9hRYz//xFWxPD//7BS9B8LGHhFRLh9VNGoolFFVFY0+MoC+gAAeVtOCLIYs+0AAAAASUVORK5CYII=',

	ICON_LOCK:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAIVBMVEX///////////////////////////////////////+ZmZmkrHixAAAAC3RSTlMAESIzVYi73e7//9NMVSMAAAAJcEhZcwAACvAAAArwAUKsNJgAAAAgdEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1Yu5EqJAAAAK5JREFUeJztlKEOglAYRkFRK49gMBhtasM3MLHRLITb3CwSncGRHeB5BZ9SQNDt7v63Kc5xyv9t94STruN0yjA8XuKF3fESSorA5gwUNfnUIq1oOFuCyud4MwvLI2fN4VDdJZxESZH59YjIJceD7XONIBCkCUWz3IS9IK25GqZGxK6dYzJBUm1SFSWVJ+9a75Wnk+K30+UmSGDefyBhoHvprtFLvdRLn5d+7y/4Dg8ab9SNFf0otQAAAABJRU5ErkJggg==',

	ICON_BACKUP_TOGGLE:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAIVBMVEX///////////////////////////////////////////9/gMdvAAAAC3RSTlMAETNEZneImczu/ynKMzkAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAWdEVYdENyZWF0aW9uIFRpbWUAMDEvMDUvMjC9Qn5kAAAAIHRFWHRTb2Z0d2FyZQBNYWNyb21lZGlhIEZpcmV3b3JrcyBNWLuRKiQAAACOSURBVHicY2AY3GAVugDXglFFKIq4VkEAkgYIWECyogXo9q3CtI9rAcgsVEUgc9AVAQlURUB5XIqYQFwF/IoYs0Dc5QI4FEHcFAm2cdVU7G6COMQCEgqrVjVj890qHACbSUgAWzgRYx1UEczhU7CHOFQRYxWIXiaAVxFSYOJRBAO0VUS1lDkKRsEoGJoAAIEZjLd7xdiCAAAAAElFTkSuQmCC',

	ICON_BACKUP_SPARE_ALLOCATE:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAJ1BMVEX///////////////////////////////////////////////////9Ruv0SAAAADXRSTlMAESIzRGZ3iJmqzO7/4p23GgAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAwMS8wNS8yML1CfmQAAAAgdEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1Yu5EqJAAAAGlJREFUeJxjYBgC4MyoIgKKeM5AABUUHSDCPp4DILMIKwISJChiJkYRTyMRbuI5nYBLEZiCKDpzygG7Ilg4QaiTCnhNIkoRXuuQFZ0OIMLhhdjVoCjCE5gIRTgBFRVRLWWOglEwCoYcAACT7lIlXCOjpwAAAABJRU5ErkJggg==',

	ICON_BACKUP_SPARE_TOGGLE:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAJFBMVEX///////////////////////////////////////////+ZmZkOWw4VAAAADHRSTlMAETNEZneImczu//+gLEI7AAAACXBIWXMAAAsSAAALEgHS3X78AAAAFnRFWHRDcmVhdGlvbiBUaW1lADAxLzA1LzIwvUJ+ZAAAACB0RVh0U29mdHdhcmUATWFjcm9tZWRpYSBGaXJld29ya3MgTVi7kSokAAAAkElEQVR4nGNgGNxgFboA14JRRSiKuFZBAJIGCFhAsqIF6Pat2g0Cu1AVgcxCVQQUWI2uCEigKgLK41LEBOIq4FfEmAXiLhfAoQjipkiwjaumYncTxCEWkFBYtaoZm+9W4QDYTEIC2MKJGOugimAOn4I9xKGKGKtA9DIBvIqQAhOPIhigrSKqpcxRMApGwdAEAOxpv2sjbcJLAAAAAElFTkSuQmCC',

	ICON_BACKUP_SPARE_REMOVE:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6AgMAAABuafceAAAAA3NCSVQICAjb4U/gAAAACVBMVEX///////+ZmZlVZlogAAAAA3RSTlMA//9EUNYhAAAACXBIWXMAAAsSAAALEgHS3X78AAAAFnRFWHRDcmVhdGlvbiBUaW1lADAxLzA1LzIwvUJ+ZAAAACB0RVh0U29mdHdhcmUATWFjcm9tZWRpYSBGaXJld29ya3MgTVi7kSokAAAAWklEQVR4nGNgGDmA0WEwCoWGhoYQFopatWoKulBoGIaQAxtWoQAgRBMKYUQRApklyorsNrCNrKEY7mJEcRpYFRYhVI1gISzGozkCJITmVCzeJkqIuFAdBdQFAHT7KqYE3Q/8AAAAAElFTkSuQmCC',

	ICON_BACKUP_SPARE_KEYPAD_ALLOCATE:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAJ1BMVEX///////////////////////////////////////////////////9Ruv0SAAAADXRSTlMAESIzRGZ3iJmqzO7/4p23GgAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAwMS8wNS8yML1CfmQAAAAgdEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1Yu5EqJAAAAGlJREFUeJxjYBgC4MyoIgKKeM5AABUUHSDCPp4DILMIKwISJChiJkYRTyMRbuI5nYBLEZiCKDpzygG7Ilg4QaiTCnhNIkoRXuuQFZ0OIMLhhdjVoCjCE5gIRTgBFRVRLWWOglEwCoYcAACT7lIlXCOjpwAAAABJRU5ErkJggg==',

	ICON_OFFSETS_RECORD:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6CAMAAAAk2e+/AAAAA3NCSVQICAjb4U/gAAAAQlBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///+7u7t3d3dEREQiIiIREREAAABtOG7kAAAAFnRSTlMAESIzRFVmd4iZqrvM3e7/////////9UBS7AAAAAlwSFlzAAAK8AAACvABQqw0mAAAACV0RVh0U29mdHdhcmUATWFjcm9tZWRpYSBGaXJld29ya3MgTVggMjAwNId2rM8AAAFbSURBVHic7dfbkoMgDAbggAeUlbS28v6vWld3q62BP7Z7sZ0x18w34SD8UvyjogM6IKF4rjch7tqqsES2qNsuhfU9goIbjaWsC8Kg4dr31yEHcUWbqrddQcibrUNk/E6Ia4mZmtoFcZlyiCrWQzmHqFwPvZymusiQyzlEbtXPeYbOgwT5vEO0rPjpXgIUxP1alw0qKLlhwuRyEG5oPE6sgMBKz9VgiC1mxlViCHUahyhAqNVBHkKKPfsuhyAudFDJqCOdQxZOTQkZ2JHiOK6g9EfLSuhnaplrRLnY9+stebEpt7+B0L4DmYGCDgoQ0n20BUNo3zWSg3ZdbNnnSLFvS0M5CK+SZRWEn6Mu6iA0uSZqoZh9sh+zDQgRQjaSHZiPkqepecpaOGiJe2e/nscpop/bnEzzSvSbqMcw2rwWRicqeFdaY2zpfCIe66D4G9ijOrF/0L/IAf1j6AYiz+j2IIE6JQAAAABJRU5ErkJggg==',

	ICON_OFFSETS_CLONE:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6BAMAAADhKQK+AAAAA3NCSVQICAjb4U/gAAAAJFBMVEX////////////////////////////////////////////////Vd7HLAAAADHRSTlMAESJEVWaImbvM7v88U0KyAAAACXBIWXMAAArwAAAK8AFCrDSYAAAAJXRFWHRTb2Z0d2FyZQBNYWNyb21lZGlhIEZpcmV3b3JrcyBNWCAyMDA0h3aszwAAABZ0RVh0Q3JlYXRpb24gVGltZQAwOS8xNy8yM4DNgIIAAACsSURBVHic7dQ9CoAwDAbQIoiewcl7uLq5eA8Xj+A9nJwdFUG/y6lQkITUKEVwaJZSff1Lo8a8iPKm8UAFJh2N2CRExwKQEB3rQPaxnZD2OLIT0h5HYuOD6KoORPfPU0DPzhEbKyPxPngKxJvlyfyqnrzQFfzcAUlRHfWBWUHpiToFRSfKtfUaYFE3lQGDimKgVpHpV92YYnK+usosaR9UZpT/5UMIKKDX/0whdv2jkkxra0CAAAAAAElFTkSuQmCC',
	
	ICON_CUE_MARK:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6AQMAAAApyY3OAAAAA3NCSVQICAjb4U/gAAAABlBMVEX///////9VfPVsAAAAAnRSTlMA/1uRIrUAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAldEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1YIDIwMDSHdqzPAAAAFnRFWHRDcmVhdGlvbiBUaW1lADAxLzA1LzIwvUJ+ZAAAAENJREFUeJxjYBikgPn///8H0FlATBSL//8HDBbxejFZxOplYPiPhXUAzjoIZx1ugLGOM8BY5+CsO/Aw+AFnfWAYrAAAWRgp/g22R+UAAAAASUVORK5CYII=',
	
	ICON_CUE_MARK_SELECTED:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6AQMAAAApyY3OAAAAA3NCSVQICAjb4U/gAAAABlBMVEX///////9VfPVsAAAAAnRSTlMA/1uRIrUAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAldEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1YIDIwMDSHdqzPAAAAFnRFWHRDcmVhdGlvbiBUaW1lADAxLzA1LzIwvUJ+ZAAAAFBJREFUeJxjYCAAmP///38AnQXERLH4/3/AYBGvF5NFrF4Ghv9YWAfgrINw1uEGGOs4A4x1Ds66Aw+DH3DWBwZU8B8CCLIg+vgHLYtYf2ACAG31cbbpM+8NAAAAAElFTkSuQmCC',
	
	ICON_CUE_MARK_NOTES:
		'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6AQMAAAApyY3OAAAAA3NCSVQICAjb4U/gAAAABlBMVEX///////9VfPVsAAAAAnRSTlMA/1uRIrUAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAldEVYdFNvZnR3YXJlAE1hY3JvbWVkaWEgRmlyZXdvcmtzIE1YIDIwMDSHdqzPAAAAFnRFWHRDcmVhdGlvbiBUaW1lADAxLzA1LzIwvUJ+ZAAAAENJREFUeJxjYCAaMP////8AOguIiWLx//+AwSJeLyaLWL0MDP+xsA7AWQfhrMMNMNZxBhjrHJx1Bx4GP+CsDwyjAAQAZNwp/qP8PfMAAAAASUVORK5CYII=',
}
